In [9]:
# Add import statements
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso

In [5]:
# Assign the data to predictor and outcome variables
# Load the data
data=np.loadtxt('datalasso.csv',delimiter=",")
X=data[:,:-1]
y=data[:,-1]


In [7]:
# Create the linear regression model.
linear_reg=LinearRegression()
# Fit the model with trainig data
linear_reg.fit(X,y)
# Retrieve and print out the coefficients 
linear_reg.coef_

array([-6.19918532e-03,  2.96325160e+00,  1.98199191e+00, -7.86249920e-02,
       -3.95818772e+00,  9.30786141e+00])

In [8]:
# Create the linear regression model with lasso regularization.
lasso_reg=Lasso()
# Fit the model with trainig data
lasso_reg.fit(X,y)
# Retrieve and print out the coefficients
lasso_reg.coef_

array([ 0.        ,  2.35793224,  2.00441646, -0.05511954, -3.92808318,
        0.        ])

In [11]:
# Create the standardization scaling object.
scaler=StandardScaler()
# Fit the standardization parameters and scale the data.
X_scaled=scaler.fit_transform(X)
# Fit the model.
lasso_reg.fit(X_scaled,y)
lasso_reg.coef_

array([  0.        ,   3.90753617,   9.02575748,  -0.        ,
       -11.78303187,   0.45340137])